<?php
declare(strict_types=1);
require dirname(__DIR__).'/app/bootstrap.php';
$siteContent=require ROOT.'/app/content.php';
start_secure_session();
$path=route_path();$method=$_SERVER['REQUEST_METHOD']??'GET';$error='';$quoteProduct=product_by_slug((string)($_GET['product']??''));
function quote_rate_limit_allows(): bool { $ip=(string)($_SERVER['REMOTE_ADDR']??'unknown');$bucket=hash_hmac('sha256',$ip,envv('APP_KEY'));$q=db()->prepare("INSERT INTO quote_rate_limits(bucket_hash,request_count,window_started_at) VALUES(?,1,NOW()) ON DUPLICATE KEY UPDATE request_count=IF(window_started_at<NOW()-INTERVAL 30 MINUTE,1,request_count+1),window_started_at=IF(window_started_at<NOW()-INTERVAL 30 MINUTE,NOW(),window_started_at)");$q->execute([$bucket]);$s=db()->prepare('SELECT request_count FROM quote_rate_limits WHERE bucket_hash=?');$s->execute([$bucket]);return (int)$s->fetchColumn()<=5; }
if($path==='/quote'&&$method==='POST'){
 csrf_check();if(trim((string)($_POST['website_url']??''))!==''){flash('Thank you. Your request has been received.');redirect('/thanks');}if(!quote_rate_limit_allows())$error='Please wait before sending another request.';$name=trim((string)($_POST['name']??''));$email=trim((string)($_POST['email']??''));$phone=trim((string)($_POST['phone']??''));$details=trim((string)($_POST['details']??''));$productId=filter_input(INPUT_POST,'product_id',FILTER_VALIDATE_INT)?:null;$configuration=[];$rawConfiguration=(isset($_POST['configuration'])&&is_array($_POST['configuration']))?$_POST['configuration']:[];foreach($rawConfiguration as $key=>$value){if(!preg_match('/^[a-z_]{1,40}$/',(string)$key)||(!is_string($value)&&!is_numeric($value))){$error='Configuration fields must be plain text values.';continue;}$value=trim((string)$value);if($value!==''&&strlen($value)>300)$error='A configuration field is too long.';if($value!=='')$configuration[$key]=$value;}$artwork=[];try{$artwork=ArtworkStorage::collect($_FILES['artwork']??[]);}catch(RuntimeException $ex){$error=$ex->getMessage();}
 $selected=null;if($productId&&!isset($configuration['quantity']))$error='Add a quantity so HDC can review the request.';if($productId){$find=db()->prepare("SELECT id,slug FROM products WHERE id=? AND status='published' AND public_visibility=1 AND production_approved=1 AND EXISTS (SELECT 1 FROM configuration_profiles cp WHERE cp.product_id=products.id AND cp.approved=1)");$find->execute([$productId]);$selected=$find->fetch();if(!$selected)$error='That service is no longer available. Please reload the form and try again.';else{$check=CommercialRules::cataloguePosterCheck($selected['slug'],$configuration);if(!$check['valid'])$error=implode(' ',$check['errors']);if(isset($configuration['quantity']))$configuration['quantity']=(int)$configuration['quantity'];if(isset($configuration['print_colors']))$configuration['print_colors']=(int)$configuration['print_colors'];}}
 if($name===''||!filter_var($email,FILTER_VALIDATE_EMAIL)||strlen($details)<12)$error='Please add your name, a valid email, and a little more detail about the job.';
 if(!$error){$stored=[];try{$stored=ArtworkStorage::store($artwork);$pdo=db();$pdo->beginTransaction();$q=$pdo->prepare("INSERT INTO quote_requests(customer_name,email,phone,details,status) VALUES(?,?,?,?,'new')");$q->execute([$name,$email,$phone,$details]);$qid=(int)$pdo->lastInsertId();if($selected){$matrixPrice=CommercialRules::exactApprovedPrice($pdo,(int)$selected['id'],$configuration);$rule=CommercialRules::cataloguePosterCheck($selected['slug'],$configuration);$sheet=CommercialRules::a3SheetBasePrice($selected['slug'],$configuration);$evaluation=['matrix_match'=>$matrixPrice!==null,'base_sheet_price'=>$sheet,'moq_rule'=>$rule,'price_total_calculated'=>false];$pdo->prepare('INSERT INTO quote_items(quote_id,product_id,configuration_json,matched_price_pkr,evaluation_json) VALUES(?,?,?,?,?)')->execute([$qid,$selected['id'],json_encode($configuration,JSON_UNESCAPED_UNICODE),$matrixPrice,json_encode($evaluation,JSON_UNESCAPED_UNICODE)]);}$meta=$pdo->prepare('INSERT INTO artwork_files(quote_id,storage_key,original_name,mime_type,byte_size) VALUES(?,?,?,?,?)');foreach($stored as $file)$meta->execute([$qid,$file['key'],$file['original'],$file['mime'],$file['size']]);$pdo->commit();flash('Your request is in. HDC will review the artwork and production details before confirming a specification or price.');redirect('/thanks');}catch(Throwable $ex){if(isset($pdo)&&$pdo instanceof PDO&&$pdo->inTransaction())$pdo->rollBack();error_log('HDC quote intake failed; retained '.count($stored).' private artwork file(s) for administrator review: '.$ex->getMessage());$error='We could not save the request. Please try again in a moment.';}}
}
$title='Hadi Digital Craft — Printing, made with intent';$content='';$products=[];$product=null;$notice=take_flash();$quotes=[];
if($path==='/'){$products=db()->query("SELECT id,name,slug,family,short_description,template FROM products WHERE status='published' AND public_visibility=1 AND production_approved=1 AND EXISTS (SELECT 1 FROM configuration_profiles cp WHERE cp.product_id=products.id AND cp.approved=1) ORDER BY sort_order,name")->fetchAll();$content='home';}
elseif($path==='/services'){$content='services';$title='Printing services — Hadi Digital Craft';}
elseif(preg_match('#^/services/([a-z0-9-]+)$#',$path,$m)&&isset($siteContent['services'][$m[1]])){$service=$siteContent['services'][$m[1]];$serviceSlug=$m[1];$content='service';$title=$service['title'].' — Hadi Digital Craft';}
elseif($path==='/finishing'){$content='finishing';$title='Finishing & embellishment — Hadi Digital Craft';}
elseif($path==='/surface-lab'){$content='surface-lab';$title='Surface Lab — Hadi Digital Craft';}
elseif($path==='/about'){$content='about';$title='About Hadi Digital Craft — HDC';}
elseif($path==='/faq'){$content='faq';$title='Frequently asked questions — HDC';}
elseif($path==='/products'){$products=db()->query("SELECT id,name,slug,family,short_description,template FROM products WHERE status='published' AND public_visibility=1 AND production_approved=1 AND EXISTS (SELECT 1 FROM configuration_profiles cp WHERE cp.product_id=products.id AND cp.approved=1) ORDER BY sort_order,name")->fetchAll();$content='catalogue';$title='Print services — Hadi Digital Craft';}
elseif(preg_match('#^/products/([a-z0-9-]+)$#',$path,$m)){$product=product_by_slug($m[1]);if(!$product||$product['status']!=='published'){http_response_code(404);$content='404';}else{$content='product';$title=$product['name'].' — Hadi Digital Craft';}}
elseif($path==='/quote'){$content='quote';$title='Request a print quote — Hadi Digital Craft';$quoteProduct=product_by_slug((string)($_GET['product']??''));$products=db()->query("SELECT id,name FROM products WHERE status='published' AND public_visibility=1 AND production_approved=1 AND EXISTS (SELECT 1 FROM configuration_profiles cp WHERE cp.product_id=products.id AND cp.approved=1) ORDER BY name")->fetchAll();}
elseif($path==='/thanks'){$content='thanks';}
elseif($path==='/admin/login'&&$method==='POST'){csrf_check();$s=db()->prepare('SELECT id,password_hash FROM admin_users WHERE email=? AND active=1');$s->execute([strtolower(trim((string)($_POST['email']??'')))]);$u=$s->fetch();if($u&&password_verify((string)($_POST['password']??''),$u['password_hash'])){session_regenerate_id(true);$_SESSION['admin_id']=$u['id'];$_SESSION['csrf']=bin2hex(random_bytes(32));redirect('/admin');}$error='Sign-in details did not match.';$content='login';$title='Admin sign in';}
elseif($path==='/admin/login'){$content='login';$title='Admin sign in';}
elseif($path==='/admin/export.csv'){require_admin();$rows=db()->query('SELECT q.id,q.customer_name,q.email,q.phone,q.details,q.status,q.created_at,p.name product_name,qi.configuration_json,qi.matched_price_pkr,j.job_reference,j.status job_status FROM quote_requests q LEFT JOIN quote_items qi ON qi.quote_id=q.id LEFT JOIN products p ON p.id=qi.product_id LEFT JOIN jobs j ON j.quote_id=q.id ORDER BY q.created_at DESC')->fetchAll();header('Content-Type: text/csv; charset=utf-8');header('Content-Disposition: attachment; filename=hdc-quote-requests.csv');header('Cache-Control: no-store, private');$out=fopen('php://output','w');fputcsv($out,['Request ID','Customer','Email','Phone','Details','Status','Received','Product','Configuration JSON','Exact approved PKR match','Job reference','Job status']);foreach($rows as $row){foreach($row as &$value){if(is_string($value)&&preg_match('/^[=+@\-\t\r]/',$value))$value="'".$value;}unset($value);fputcsv($out,$row);}fclose($out);exit;}
elseif($path==='/admin/artwork'){require_admin();$id=filter_input(INPUT_GET,'id',FILTER_VALIDATE_INT);$q=db()->prepare('SELECT * FROM artwork_files WHERE id=?');$q->execute([$id]);$file=$q->fetch();if(!$file){http_response_code(404);exit('Not found');}$base=realpath(ROOT.'/storage/private-artwork');$target=realpath(ROOT.'/storage/private-artwork/'.$file['storage_key']);if(!$base||!$target||!str_starts_with($target,$base.DIRECTORY_SEPARATOR)||!is_file($target)){http_response_code(404);exit('Not found');}$log=db()->prepare("INSERT INTO audit_events(admin_id,event_type,entity_type,entity_id,details_json) VALUES(?,'artwork_downloaded','quote',?,JSON_OBJECT('file_id',?))");$log->execute([$_SESSION['admin_id'],$file['quote_id'],$id]);header('Content-Type: application/octet-stream');header('X-Content-Type-Options: nosniff');header('Cache-Control: private, no-store');header('Content-Length: '.filesize($target));header('Content-Disposition: attachment; filename="'.rawurlencode($file['original_name']).'"');readfile($target);exit;}
elseif($path==='/admin/logout'&&$method==='POST'){csrf_check();$_SESSION=[];session_destroy();redirect('/admin/login');}
elseif($path==='/admin'){require_admin();$content='admin';$title='ORVIA review desk';$quotes=db()->query('SELECT q.*,p.name product_name,qi.matched_price_pkr,qi.evaluation_json FROM quote_requests q LEFT JOIN quote_items qi ON qi.quote_id=q.id LEFT JOIN products p ON p.id=qi.product_id ORDER BY q.created_at DESC LIMIT 100')->fetchAll();$jobs=db()->query('SELECT * FROM jobs ORDER BY updated_at DESC LIMIT 100')->fetchAll();$artworkByQuote=[];foreach(db()->query('SELECT id,quote_id,original_name FROM artwork_files ORDER BY id') as $file){$artworkByQuote[(int)$file['quote_id']][]=$file;}$products=db()->query('SELECT p.*,(SELECT profile_json FROM configuration_profiles cp WHERE cp.product_id=p.id ORDER BY cp.id DESC LIMIT 1) profile_json FROM products p ORDER BY p.sort_order,p.name')->fetchAll();}
elseif($path==='/admin/job'&&$method==='POST'){require_admin();csrf_check();$quoteId=(int)($_POST['quote_id']??0);$q=db()->prepare("SELECT q.id,q.status,qi.configuration_json,p.name FROM quote_requests q LEFT JOIN quote_items qi ON qi.quote_id=q.id LEFT JOIN products p ON p.id=qi.product_id WHERE q.id=?");$q->execute([$quoteId]);$row=$q->fetch();if(!$row||$row['status']!=='quoted'){flash('Set the request to quoted before creating a job record.');redirect('/admin');}$ref='HDC-'.date('ymd').'-'.strtoupper(bin2hex(random_bytes(3)));$spec=['quote_id'=>$quoteId,'product'=>$row['name'],'configuration'=>json_decode($row['configuration_json']??'{}',true),'accepted_by_customer'=>false];$create=db()->prepare("INSERT IGNORE INTO jobs(quote_id,job_reference,status,specification_snapshot) VALUES(?,?,'awaiting_customer_approval',?)");$create->execute([$quoteId,$ref,json_encode($spec,JSON_UNESCAPED_UNICODE)]);if($create->rowCount()){$log=db()->prepare("INSERT INTO audit_events(admin_id,event_type,entity_type,entity_id,details_json) VALUES(?,'job_created','quote',?,JSON_OBJECT('job_reference',?))");$log->execute([$_SESSION['admin_id'],$quoteId,$ref]);flash('Job record created. Customer approval remains pending.');}else flash('A job already exists for this quote.');redirect('/admin');}
elseif($path==='/admin/job/status'&&$method==='POST'){require_admin();csrf_check();$id=(int)($_POST['id']??0);$allowed=['awaiting_customer_approval','approved','in_production','quality_check','ready','completed','on_hold','cancelled'];$status=(string)($_POST['status']??'awaiting_customer_approval');if(!in_array($status,$allowed,true))$status='awaiting_customer_approval';$q=db()->prepare('UPDATE jobs SET status=?,updated_at=NOW() WHERE id=?');$q->execute([$status,$id]);$log=db()->prepare("INSERT INTO audit_events(admin_id,event_type,entity_type,entity_id,details_json) VALUES(?,'job_status_changed','job',?,JSON_OBJECT('status',?))");$log->execute([$_SESSION['admin_id'],$id,$status]);flash('Job status updated.');redirect('/admin');}
elseif($path==='/admin/quote'&&$method==='POST'){require_admin();csrf_check();$id=(int)($_POST['id']??0);$allowed=['new','in_review','awaiting_customer','quoted','closed'];$status=(string)($_POST['status']??'new');if(!in_array($status,$allowed,true))$status='new';$s=db()->prepare('UPDATE quote_requests SET status=?,updated_at=NOW() WHERE id=?');$s->execute([$status,$id]);$log=db()->prepare("INSERT INTO audit_events(admin_id,event_type,entity_type,entity_id,details_json) VALUES(?,'quote_status_changed','quote',?,JSON_OBJECT('status',?))");$log->execute([$_SESSION['admin_id'],$id,$status]);flash('Quote status updated.');redirect('/admin');}
elseif($path==='/admin/price'&&$method==='POST') {require_admin();csrf_check();$productId=(int)($_POST['product_id']??0);$rawConfig=(string)($_POST['configuration_json']??'');$config=json_decode($rawConfig,true);$configObject=json_decode($rawConfig);$price=filter_var($_POST['price_pkr']??null,FILTER_VALIDATE_FLOAT);$s=db()->prepare("SELECT slug FROM products WHERE id=? AND status='published' AND public_visibility=1 AND production_approved=1 AND EXISTS (SELECT 1 FROM configuration_profiles cp WHERE cp.product_id=products.id AND cp.approved=1)");$s->execute([$productId]);$p=$s->fetch();if(!$p||!is_array($config)||!is_object($configObject)||$price===false||$price<=0){flash('Price row not saved. Select an approved product, a JSON configuration object and a positive PKR amount.');redirect('/admin');}$check=CommercialRules::cataloguePosterCheck($p['slug'],$config);if(!$check['valid']){flash(implode(' ',$check['errors']));redirect('/admin');}$hash=CommercialRules::priceHash($config);$q=db()->prepare('INSERT INTO price_matrix(product_id,configuration_hash,price_pkr,approved,approved_by,approved_at) VALUES(?,?,?,1,?,NOW()) ON DUPLICATE KEY UPDATE price_pkr=VALUES(price_pkr),approved=1,approved_by=VALUES(approved_by),approved_at=NOW()');$q->execute([$productId,$hash,number_format((float)$price,2,'.',''),$_SESSION['admin_id']]);$log=db()->prepare("INSERT INTO audit_events(admin_id,event_type,entity_type,entity_id,details_json) VALUES(?,'price_matrix_row_approved','product',?,JSON_OBJECT('hash',?,'price_pkr',?))");$log->execute([$_SESSION['admin_id'],$productId,$hash,(float)$price]);flash('Exact price row approved. No formula or fallback price was created.');redirect('/admin');}
elseif($path==='/admin/product'&&$method==='POST'){require_admin();csrf_check();$id=(int)($_POST['id']??0);$status=(($_POST['status']??'draft')==='published')?'published':'draft';$approved=isset($_POST['production_approved'])?1:0;$visible=isset($_POST['public_visibility'])?1:0;$note=trim((string)($_POST['approval_note']??''));$d=trim((string)($_POST['description']??''));$s=trim((string)($_POST['short_description']??''));$rawProfile=(string)($_POST['profile_json']??'');$profile=json_decode($rawProfile,true);$profileObject=json_decode($rawProfile);if(!is_array($profile)||!is_object($profileObject)){flash('Profile must be a valid JSON object before saving.');redirect('/admin');}if(!$approved||!$visible||!$profile)$status='draft';$q=db()->prepare('UPDATE products SET status=?,public_visibility=?,production_approved=?,approved_by=?,approved_at=IF(?,NOW(),NULL),approval_note=?,short_description=?,description=?,updated_at=NOW() WHERE id=?');$q->execute([$status,$visible,$approved,$_SESSION['admin_id'],$approved,$note,$s,$d,$id]);$p=db()->prepare('INSERT INTO configuration_profiles(product_id,profile_json,approved,approved_by,approved_at) VALUES(?,?,?,?,IF(?,NOW(),NULL))');$p->execute([$id,json_encode($profile,JSON_UNESCAPED_UNICODE),$approved,$_SESSION['admin_id'],$approved]);$log=db()->prepare("INSERT INTO audit_events(admin_id,event_type,entity_type,entity_id,details_json) VALUES(?,'product_review_saved','product',?,JSON_OBJECT('status',?,'approved',?,'visible',?,'note',?))");$log->execute([$_SESSION['admin_id'],$id,$status,$approved,$visible,$note]);flash('Product review saved.');redirect('/admin');}
else{http_response_code(404);$content='404';}
require ROOT.'/app/view.php';
